spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ulti_insights
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_mysql_user
    password: your_mysql_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
