package com.kugel.ulti_insights;

public enum League {
  MENS_COLLEGE_D1,
  MENS_COLLEGE_D3,
  WOMENS_COLLEGE_D1,
  WOMENS_COLLEGE_D3,
  MIXED_CLUB,
  MENS_CLUB,
  WOMENS_CLUB,
  WOMENS_YCC_U17,
  OTHER,
  MENS_YCC_U20,
  WOMENS_YCC_U20,
  MIXED_YCC_U20,
  MIXED_YCC_U17,
  MENS_YCC_U17
}

